SLOW_ATTACK = 5
MEDIUM_ATTACK = 3
FAST_ATTACK = 1

SLOW_SPEED = 1
MEDIUM_SPEED = 3
FAST_SPEED = 5
TOP_SPEED = 6

FPS = 10
SCALING_FACTOR = 0.7
WIDTH = int(540*SCALING_FACTOR)
HEIGHT = int(1080*SCALING_FACTOR)
FULL_WIDTH = int(1960*SCALING_FACTOR)
FULL_HEIGHT = int(1080*SCALING_FACTOR)
ARENA_WIDTH = int(422*SCALING_FACTOR)
ARENA_HEIGHT = int(844*SCALING_FACTOR)

FRAMES = 6
GAME_START_TIME = 3*FRAMES # 3 sec
GAME_TOTAL_TIME = 1800 # 3 min
GAME_END_TIME = GAME_START_TIME + GAME_TOTAL_TIME